version: '3.8'
networks:
   orbiter-network:
    external: true
    labels:
      - "com.docker.compose.project=explore-openapi"
services:
  openapi:
    container_name: "explore-openapi"
    image: orbiter/explore-openapi:latest
    labels:
      - "com.docker.compose.project=explore-openapi"
    build:
      context: ./
      cache_from:
        - orbiter/clients
      dockerfile:  ./apps/explore-open-api/Dockerfile.clients
    restart: always
    env_file: .env
    environment:
      CONSUL_URL: '${CONSUL_URL}'
    ports:
      - '9001:3000'
    networks:
      - orbiter-network
    volumes:
      - './sheet-377710-b8d7c8d145e9.json:/app/google/sheet-377710-b8d7c8d145e9.json'
      - './runtime:/app/runtime'
      - './logs:/app/logs'
